# Generated by Django 4.2.2 on 2023-06-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band_alter_listing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='band',
        ),
    ]
